### ISSUE TITLE
Error in Node Module

### ISSUE THREAD

**Issue by dylanjamesdev** [Androz2091/discord-giveaways-bot#71]
```[Unhandled Rejection] TypeError: member.hasPermission is not a function
    at /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:82
    at Array.some (<anonymous>)
    at Giveaway.checkWinnerEntry (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:306:54)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Giveaway.roll (/Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:340:46)
    at async /Users/dylan/Desktop/Projects/Tritan-Bot/node_modules/discord-giveaways/src/Giveaway.js:400:29```

**Comment by Nico105** [comment]
`npm install Androz2091/discord-giveaways#develop` is the fix, with the next release it will be in the master branch

**Comment by Nico105** [comment]
> `npm install Androz2091/discord-giveaways#develop` is the fix, with the next release it will be in the master branch

_I know I already told you in the module repo😉but I repeat it for people who might see this in the future_

**Comment by Nico105** [comment]
Nvm, Androz release a new `discord-giveaways` version with the fix, so just update it with `npm update discord-giveaways`
