### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mitul009** [Androz2091/discord-giveaways-bot#73]
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined

**Comment by loveisglitchy** [comment]
Umm can you provide some context?

**Comment by RocketFlashXD** [comment]
I could elaborate a little since it happened to me too. Basically when the giveaway ends it throws that error with the source of the error being the Giveaways.js file from the discord-giveaways package

(node:43148) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Giveaway.checkWinnerEntry (C:\[I prefer not to show this part]\node_modules\discord-giveaways\src\Giveaway.js:302:42)
    at Giveaway.roll (C:\[I prefer not to show this part]\node_modules\discord-giveaways\src\Giveaway.js:333:45)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\[I prefer not to show this part]\node_modules\discord-giveaways\src\Giveaway.js:400:29

**Comment by Androz2091** [comment]
this has been fixed
