### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dergrosehd** [Androz2091/discord-giveaways-bot#92]
I tried to code a bot with the discord-giveaways package but an error came. Now I cloned the github repo and the same error came. Can anyone help me?

```
C:\[.....]\node_modules\discord-giveaways\src\Manager.js:368
                giveaway.message ??= await giveaway.fetchMessage().catch(() => {});
                                 ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\[.....]\node_modules\discord-giveaways\index.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by Nico105** [comment]
dc-gaws is built for discord.js v13
And v13 requires node.js v16.6 = so we do it too, since we use features feom 16.6
You need to update

**Comment by dergrosehd** [comment]
I have the newest version of 14.16.1! What another can be the problem?

**Comment by Nico105** [comment]
> I have the newest version of 14.16.1! What another can be the problem?

Idk if you didn't read my comment correctly.
But you need node.js 16.6.

**Comment by dergrosehd** [comment]
Now I have 16.3.0
but there is another error

**Comment by Nico105** [comment]
> Now I have 16.3.0
> but there is another error

16.6

**Comment by dergrosehd** [comment]
https://blog.risingstack.com/update-node-js-latest-version/
There is no 16.6 for Windows

**Comment by Nico105** [comment]
> Now I have 16.3.0
> but there is another error
> 
> DiscordAPIError: Missing Access

did you adjust the guildId in the config file?

**Comment by dergrosehd** [comment]
Yes

**Comment by dergrosehd** [comment]
There is also no 16.6 only 16.9

**Comment by Nico105** [comment]
> Yes

can you send the full error path, if there is one.

**Comment by Nico105** [comment]
> There is also no 16.6 only 16.9

doesn't matter. it just has to be "at least" 16.6

**Comment by dergrosehd** [comment]
`C:\[.....]\node_modules\discord.js\src\rest\RequestHandler.js:298
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Access
    at RequestHandler.execute (C:\[.....]\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\[.....]\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async ApplicationCommandManager.fetch (C:\[.....]\node_modules\discord.js\src\managers\ApplicationCommandManager.js:97:18)
    at async module.exports (C:\[.....]\node_modules\discord-sync-commands\index.js:12:29) {
  method: 'get',
  path: '/applications/884819497356251198/guilds/859828412307079198/commands',
  code: 50001,
  httpStatus: 403,
  requestData: { json: undefined, files: [] }
}`

**Comment by dergrosehd** [comment]
Now I have 16.9.0 and the same API Error came

**Comment by Nico105** [comment]
> `C:[.....]\node_modules\discord.js\src\rest\RequestHandler.js:298
> throw new DiscordAPIError(data, res.status, request);
> ^
> 
> DiscordAPIError: Missing Access
> at RequestHandler.execute (C:[.....]\node_modules\discord.js\src\rest\RequestHandler.js:298:13)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async RequestHandler.push (C:[.....]\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
> at async ApplicationCommandManager.fetch (C:[.....]\node_modules\discord.js\src\managers\ApplicationCommandManager.js:97:18)
> at async module.exports (C:[.....]\node_modules\discord-sync-commands\index.js:12:29) {
> method: 'get',
> path: '/applications/884819497356251198/guilds/859828412307079198/commands',
> code: 50001,
> httpStatus: 403,
> requestData: { json: undefined, files: [] }
> }`

ah, you will have to kick your bot.
and when you invite him again, inside the invite link you have to include/edit `scope=applications.commands%20bot`,

**Comment by Nico105** [comment]
> Now I have 16.9.0 and the same API Error came

*the api error is not related to the version*

**Comment by dergrosehd** [comment]
Thanks now everything works
